# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

loc = Location.create(name: 'Birmingport ECA')
Code.create(location: loc, code: 'II.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'II.B', name: 'O & M')
Code.create(location: loc, code: 'II.C', name: 'New Envirnmental Actions')
Code.create(location: loc, code: 'II.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'II.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'II.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'II.G', name: 'Legal Costs')
Code.create(location: loc, code: 'II.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'II.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Mobile ECA')
Code.create(location: loc, code: 'III.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'III.B', name: 'O & M')
Code.create(location: loc, code: 'III.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'III.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'III.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'III.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'III.G', name: 'Legal Costs')
Code.create(location: loc, code: 'III.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'III.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Jacksonville AgCh ECA')
Code.create(location: loc, code: 'IV.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'IV.B', name: 'O & M')
Code.create(location: loc, code: 'IV.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'IV.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'IV.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'IV.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'IV.G', name: 'Legal Costs')
Code.create(location: loc, code: 'IV.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'IV.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Jacksonville AgCh SA')
Code.create(location: loc, code: 'V.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'V.B', name: 'O & M')
Code.create(location: loc, code: 'V.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'V.D', name: 'MST Technical Team/Project Mg')
Code.create(location: loc, code: 'V.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'V.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'V.G', name: 'Legal Costs')
Code.create(location: loc, code: 'V.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'V.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Jacksonville PT ECA')
Code.create(location: loc, code: 'VI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'VI.B', name: 'O & M')
Code.create(location: loc, code: 'VI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'VI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'VI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'VI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'VI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'VI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'VI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Soda Springs ECA')
Code.create(location: loc, code: 'VII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'VII.B', name: 'O & M')
Code.create(location: loc, code: 'VII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'VII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'VII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'VII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'VII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'VII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'VII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Madison ECA')
Code.create(location: loc, code: 'VIII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'VIII.B', name: 'O & M')
Code.create(location: loc, code: 'VIII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'VIII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'VIII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'VIII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'VIII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'VIII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'VIII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Sauget ECA')
Code.create(location: loc, code: 'IX.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'IX.B', name: 'O & M')
Code.create(location: loc, code: 'IX.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'IX.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'IX.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'IX.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'IX.G', name: 'Legal Costs')
Code.create(location: loc, code: 'IX.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'IX.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Indianapolis ECA')
Code.create(location: loc, code: 'X.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'X.B', name: 'O & M')
Code.create(location: loc, code: 'X.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'X.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'X.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'X.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'X.G', name: 'Legal Costs')
Code.create(location: loc, code: 'X.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'X.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Rushville ECA')
Code.create(location: loc, code: 'XI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XI.B', name: 'O & M')
Code.create(location: loc, code: 'XI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Bossier City ECA')
Code.create(location: loc, code: 'XII', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XII.B', name: 'O & M')
Code.create(location: loc, code: 'XII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Calhoun ECA')
Code.create(location: loc, code: 'XIII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XIII.B', name: 'O & M')
Code.create(location: loc, code: 'XIII.C', name: 'New Envirnomental Actions')
Code.create(location: loc, code: 'XIII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XIII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XIII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XIII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XIII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XIII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Kansas City ECA')
Code.create(location: loc, code: 'XIV.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XIV.B', name: 'O & M')
Code.create(location: loc, code: 'XIV.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XIV.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XIV.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XIV.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XIV.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XIV.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XIV.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Springfield ECA')
Code.create(location: loc, code: 'XV.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XV.B', name: 'O & M')
Code.create(location: loc, code: 'XV.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XV.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XV.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XV.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XV.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XV.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XV.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Columbus ECA')
Code.create(location: loc, code: 'XVI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XVI.B', name: 'O & M')
Code.create(location: loc, code: 'XVI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XVI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XVI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XVI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XVI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XVI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XVI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Columbus SA')
Code.create(location: loc, code: 'XVII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XVII.B', name: 'O & M')
Code.create(location: loc, code: 'XVII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XVII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XVII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XVII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XVII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XVII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XVII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Meridian ECA')
Code.create(location: loc, code: 'XVIII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XVIII.B', name: 'O & M')
Code.create(location: loc, code: 'XVIII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XVIII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XVIII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XVIII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XVIII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XVIII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XVIII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Meridian SA')
Code.create(location: loc, code: 'XIX.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XIX.B', name: 'O & M')
Code.create(location: loc, code: 'XIX.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XIX.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XIX.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XIX.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XIX.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XIX.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XIX.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Navassa ECA')
Code.create(location: loc, code: 'XX.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XX.B', name: 'O & M')
Code.create(location: loc, code: 'XX.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XX.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XX.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XX.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XX.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XX.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XX.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Navassa SA')
Code.create(location: loc, code: 'XXI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXI.B', name: 'O & M')
Code.create(location: loc, code: 'XXI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Bristol ECA')
Code.create(location: loc, code: 'XXII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXII.B', name: 'O & M')
Code.create(location: loc, code: 'XXII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Caselton ECA')
Code.create(location: loc, code: 'XXIII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXIII.B', name: 'O & M')
Code.create(location: loc, code: 'XXIII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXIII.D', name: 'MST Techincal Team/Project Mgmt')
Code.create(location: loc, code: 'XXIII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXIII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXIII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXIII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXIII.I', name: 'Lease & Property Use')

loc = Location.create(name: 'Rome ECA')
Code.create(location: loc, code: 'XXIV.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXIV.B', name: 'O & M')
Code.create(location: loc, code: 'XXIV.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXIV.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXIV.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXIV.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXIV.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXIV.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XIV.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Cleveland ECA')
Code.create(location: loc, code: 'XXV.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXV.B', name: 'O & M')
Code.create(location: loc, code: 'XXV.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXV.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXV.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXV.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXV.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXV.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXV.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Cushing ECA')
Code.create(location: loc, code: 'XXVI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXVI.B', name: 'O & M')
Code.create(location: loc, code: 'XXVI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXVI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXVI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXVI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXVI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXVI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXVI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Avoca ECA')
Code.create(location: loc, code: 'XXVII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXVII.B', name: 'O & M')
Code.create(location: loc, code: 'XXVII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXVII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXVII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXVII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXVII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXVII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXVII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Beaumont ECA')
Code.create(location: loc, code: 'XXVIIIA', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXVIIIB', name: 'O & M')
Code.create(location: loc, code: 'XXVIIIC', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXVIIID', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXVIIIE', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXVIIIF', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXVIIIG', name: 'Legal Costs')
Code.create(location: loc, code: 'XXVIIIH', name: 'Accounting Costs')
Code.create(location: loc, code: 'XVIIII', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Corpus Christi ECA')
Code.create(location: loc, code: 'XXIX.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXIX.B', name: 'O & M')
Code.create(location: loc, code: 'XXIX.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXIX.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXIX.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXIX.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXIX.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXIX.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXIX.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Texarkana ECA')
Code.create(location: loc, code: 'XXX.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXX.B', name: 'O & M')
Code.create(location: loc, code: 'XXX.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXX.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXX.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXX.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXX.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXX.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXX.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'Owned Service Stations ECA')
Code.create(location: loc, code: 'XXXI.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXXI.B', name: 'O & M')
Code.create(location: loc, code: 'XXXI.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXXI.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXXI.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXXI.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXXI.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXXI.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXXI.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'MST Work ECA')
Code.create(location: loc, code: 'XXXII.A', name: 'Regulatory Compliance')
Code.create(location: loc, code: 'XXXII.B', name: 'O & M')
Code.create(location: loc, code: 'XXXII.C', name: 'New Environmental Actions')
Code.create(location: loc, code: 'XXXII.D', name: 'MST Technical Team/Project Mgmt')
Code.create(location: loc, code: 'XXXII.E', name: 'Trustee Fees & Expenses')
Code.create(location: loc, code: 'XXXII.F', name: 'Regulator Oversight Costs')
Code.create(location: loc, code: 'XXXII.G', name: 'Legal Costs')
Code.create(location: loc, code: 'XXXII.H', name: 'Accounting Costs')
Code.create(location: loc, code: 'XXXII.I', name: 'Lease & Property Use - Inc & Exp')

loc = Location.create(name: 'MST AA')
Code.create(location: loc, code: 'I.A', name: 'Financial Affairs')
Code.create(location: loc, code: 'I.B', name: 'Taxes')
Code.create(location: loc, code: 'I.C', name: 'Site Security & Property Mgmt')
Code.create(location: loc, code: 'I.C.10', name: 'Site Security & Property Mgmt:I.C.10 - Indianapolis ECA')
Code.create(location: loc, code: 'I.C.11', name: 'Site Security & Property Mgmt:I.C.11 - Rushville ECA')
Code.create(location: loc, code: 'I.C.12', name: 'Site Security & Property Mgmt:I.C.12 - Bossier City ECA')
Code.create(location: loc, code: 'I.C.13', name: 'Site Security & Property Mgmt:I.C.13 - Calhoun ECA')
Code.create(location: loc, code: 'I.C.14', name: 'Site Security & Property Mgmt:I.C.14 - Kansas City ECA')
Code.create(location: loc, code: 'I.C.15', name: 'Site Security & Property Mgmt:I.C.15 - Springfield ECA')
Code.create(location: loc, code: 'I.C.16', name: 'Site Security & Property Mgmt:I.C.16 - Columbus ECA')
Code.create(location: loc, code: 'I.C.17', name: 'Site Security & Property Mgmt:I.C.17 - Columbus SA')
Code.create(location: loc, code: 'I.C.18', name: 'Site Security & Property Mgmt:I.C.18 - Meridian ECA')
Code.create(location: loc, code: 'I.C.19', name: 'Site Security & Property Mgmt:I.C.19 - Meridian SA')
Code.create(location: loc, code: 'I.C.2', name: 'Site Security & Property Mgmt:I.C.2 - Birmingport ECA')
Code.create(location: loc, code: 'I.C.20', name: 'Site Security & Property Mgmt:I.C.20 - Navassa ECA')
Code.create(location: loc, code: 'I.C.21', name: 'Site Security & Property Mgmt:I.C.21 - Navassa SA')
Code.create(location: loc, code: 'I.C.22', name: 'Site Security & Property Mgmt:I.C.22 - Bristol ECA')
Code.create(location: loc, code: 'I.C.23', name: 'Site Security & Property Mgmt:I.C.23 - Caselton ECA')
Code.create(location: loc, code: 'I.C.24', name: 'Site Security & Property Mgmt:I.C.24 - Rome ECA')
Code.create(location: loc, code: 'I.C.25', name: 'Site Security & Property Mgmt:I.C.25 - Cleveland ECA')
Code.create(location: loc, code: 'I.C.26', name: 'Site Security & Property Mgmt:I.C.26 - Cushing ECA')
Code.create(location: loc, code: 'I.C.27', name: 'Site Security & Property Mgmt:I.C.27 - Avoca ECA')
Code.create(location: loc, code: 'I.C.28', name: 'Site Security & Property Mgmt:I.C.28 - Beaumont ECA')
Code.create(location: loc, code: 'I.C.29', name: 'Site Security & Property Mgmt:I.C.29 - Corpus Christi ECA')
Code.create(location: loc, code: 'I.C.3', name: 'Site Security & Property Mgmt:I.C.3 - Mobile ECA')
Code.create(location: loc, code: 'I.C.30', name: 'Site Security & Property Mgmt:I.C.30 - Texarkana ECA')
Code.create(location: loc, code: 'I.C.31', name: 'Site Security & Property Mgmt:I.C.31 - Owned Service Stations ECA')
Code.create(location: loc, code: 'I.C.32', name: 'Site Security & Property Mgmt:I.C.32 - MST Work Acct')
Code.create(location: loc, code: 'I.C.4', name: 'Site Security & Property Mgmt:I.C.4 - Jacksonville AgCh ECA')
Code.create(location: loc, code: 'I.C.5', name: 'Site Security & Property Mgmt:I.C.5 - Jacksonville AgCh SA')
Code.create(location: loc, code: 'I.C.6', name: 'Site Security & Property Mgmt:I.C.6 - Jacksonsonville PT ECA')
Code.create(location: loc, code: 'I.C.7', name: 'Site Security & Property Mgmt:I.C.7 - Soda Springs ECA')
Code.create(location: loc, code: 'I.C.8', name: 'Site Security & Property Mgmt:I.C.8 - Madison ECA')
Code.create(location: loc, code: 'I.C.9', name: 'Site Security & Property Mgmt:I.C.9 - Sauget ECA')
Code.create(location: loc, code: 'I.D', name: 'Insurance')
Code.create(location: loc, code: 'I.E', name: 'Trustee Fee & Expenses')
Code.create(location: loc, code: 'I.F', name: 'Legal Affairs')
Code.create(location: loc, code: 'I.G', name: 'Overall Trust IT/Records/Docs')
Code.create(location: loc, code: 'I.H', name: 'Pre-Effective Date Fees & Exps')
Code.create(location: loc, code: 'I.I', name: 'MST Leases')
