loc = Location.create(name: 'Birmingport ECA')
  code = Code.create(location: loc, code: 'II.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'II.B', name: 'O & M')
  code = Code.create(location: loc, code: 'II.C', name: 'New Envirnmental Actions')
  code = Code.create(location: loc, code: 'II.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'II.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'II.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'II.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'II.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'II.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Mobile ECA')
  code = Code.create(location: loc, code: 'III.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'III.B', name: 'O & M')
  code = Code.create(location: loc, code: 'III.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'III.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'III.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'III.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'III.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Review and email C. Neuberger re Mobile, AL combined sales, lease and use tax forms')
  code = Code.create(location: loc, code: 'III.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'III.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Jacksonville AgCh ECA')
  code = Code.create(location: loc, code: 'IV.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'IV.B', name: 'O & M')
  code = Code.create(location: loc, code: 'IV.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'IV.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'IV.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'IV.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'IV.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'IV.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'IV.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Jacksonville AgCh SA')
  code = Code.create(location: loc, code: 'V.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'V.B', name: 'O & M')
  code = Code.create(location: loc, code: 'V.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'V.D', name: 'MST Technical Team/Project Mg')
  code = Code.create(location: loc, code: 'V.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'V.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'V.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'V.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'V.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Jacksonville PT ECA')
  code = Code.create(location: loc, code: 'VI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'VI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'VI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'VI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'VI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'VI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'VI.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Email and tel. conf. w/ S. Denlinger and T. Griffith re wire transfer instructions for Jacksonville Terminal Site ECA')
  code = Code.create(location: loc, code: 'VI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'VI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Soda Springs ECA')
  code = Code.create(location: loc, code: 'VII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'VII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'VII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'VII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'VII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'VII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'VII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'VII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'VII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Madison ECA')
  code = Code.create(location: loc, code: 'VIII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'VIII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'VIII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'VIII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'VIII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'VIII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'VIII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'VIII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'VIII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Sauget ECA')
  code = Code.create(location: loc, code: 'IX.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'IX.B', name: 'O & M')
  code = Code.create(location: loc, code: 'IX.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'IX.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'IX.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'IX.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'IX.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'IX.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'IX.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Indianapolis ECA')
  code = Code.create(location: loc, code: 'X.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'X.B', name: 'O & M')
  code = Code.create(location: loc, code: 'X.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'X.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'X.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'X.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'X.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'X.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'X.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Rushville ECA')
  code = Code.create(location: loc, code: 'XI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XI.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Bossier City ECA')
  code = Code.create(location: loc, code: 'XII', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Calhoun ECA')
  code = Code.create(location: loc, code: 'XIII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XIII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XIII.C', name: 'New Envirnomental Actions')
  code = Code.create(location: loc, code: 'XIII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XIII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XIII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XIII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XIII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XIII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Kansas City ECA')
  code = Code.create(location: loc, code: 'XIV.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XIV.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XIV.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XIV.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XIV.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XIV.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XIV.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XIV.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XIV.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Springfield ECA')
  code = Code.create(location: loc, code: 'XV.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XV.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XV.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XV.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XV.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XV.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XV.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ E. Roth regarding accident at Springfield site')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ E. Roth regarding Procter property (Springfield)')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ E. Roth regarding Green Property (Springfield)')
    WorkEntry.create(code: code, worked_at: '2011-11-09', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Email T. Griffith and E. Roth re Springfield (N. Clifton) fence damage and insurance information')
    WorkEntry.create(code: code, worked_at: '2011-11-18', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email M. Weinreich re access issues affecting Greene Property and Proctor Property in Springfield')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Corresp. w/ M. Paque and M. Weinreich re release of Springfield surety bond')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email M. Weinreich and M. Paque re Springfield wells')
    WorkEntry.create(code: code, worked_at: '2011-11-23', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ E. Roth re status of Proctor and Green access agreements')
    WorkEntry.create(code: code, worked_at: '2011-11-23', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ E. Roth and M. Weinreich re Proctor and Green properties')
    WorkEntry.create(code: code, worked_at: '2011-11-28', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Prepare summary memo re discussion of Proctor and Greene Properties w/ M. Weinreich and E. Roth; review E. Roth summary memo dated 8/2/11')
  code = Code.create(location: loc, code: 'XV.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XV.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Columbus ECA')
  code = Code.create(location: loc, code: 'XVI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XVI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XVI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XVI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XVI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XVI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XVI.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XVI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XVI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Columbus SA')
  code = Code.create(location: loc, code: 'XVII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XVII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XVII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XVII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XVII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XVII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XVII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XVII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XVII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Meridian ECA')
  code = Code.create(location: loc, code: 'XVIII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XVIII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XVIII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XVIII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XVIII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XVIII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XVIII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XVIII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XVIII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Meridian SA')
  code = Code.create(location: loc, code: 'XIX.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XIX.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XIX.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XIX.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XIX.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XIX.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XIX.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XIX.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XIX.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Navassa ECA')
  code = Code.create(location: loc, code: 'XX.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XX.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XX.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XX.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XX.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XX.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XX.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XX.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XX.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Navassa SA')
  code = Code.create(location: loc, code: 'XXI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXI.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Bristol ECA')
  code = Code.create(location: loc, code: 'XXII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Caselton ECA')
  code = Code.create(location: loc, code: 'XXIII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXIII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXIII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXIII.D', name: 'MST Techincal Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXIII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXIII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXIII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXIII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXIII.I', name: 'Lease & Property Use')
loc = Location.create(name: 'Rome ECA')
  code = Code.create(location: loc, code: 'XXIV.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXIV.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXIV.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXIV.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXIV.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXIV.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXIV.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXIV.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XIV.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Cleveland ECA')
  code = Code.create(location: loc, code: 'XXV.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXV.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXV.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXV.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXV.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXV.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXV.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXV.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXV.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Cushing ECA')
  code = Code.create(location: loc, code: 'XXVI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXVI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXVI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXVI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXVI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXVI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXVI.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXVI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXVI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Avoca ECA')
  code = Code.create(location: loc, code: 'XXVII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXVII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXVII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXVII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXVII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXVII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXVII.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXVII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXVII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Beaumont ECA')
  code = Code.create(location: loc, code: 'XXVIIIA', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXVIIIB', name: 'O & M')
  code = Code.create(location: loc, code: 'XXVIIIC', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXVIIID', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXVIIIE', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXVIIIF', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXVIIIG', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXVIIIH', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XVIIII', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Corpus Christi ECA')
  code = Code.create(location: loc, code: 'XXIX.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXIX.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXIX.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXIX.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXIX.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXIX.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXIX.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXIX.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXIX.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Texarkana ECA')
  code = Code.create(location: loc, code: 'XXX.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXX.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXX.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXX.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXX.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXX.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXX.G', name: 'Legal Costs')
  code = Code.create(location: loc, code: 'XXX.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXX.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'Owned Service Stations ECA')
  code = Code.create(location: loc, code: 'XXXI.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXXI.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXXI.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXXI.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXXI.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXXI.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXXI.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-02', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Fryer re Harrodsburg conveyance')
    WorkEntry.create(code: code, worked_at: '2011-11-03', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ S. Denlinger re establishing Bar-Co segregated subaccount for conveyance proceeds')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review corresp. re proposed Kokomo, IN easement')
    WorkEntry.create(code: code, worked_at: '2011-11-15', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Follow up re BOV letter for Muscatine Ave., Iowa City property')
    WorkEntry.create(code: code, worked_at: '2011-11-15', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review tax assessment appointment correspondence re Davenport, IA')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Review N. College St., Harrodsburg materials; draft Memorandum in Support of Property Transaction re same')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Prepare lease inquiry response email re 4525 Washington Ave., Houston, TX')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ Shawn Moore of Mercer County, KY Planning Department re Harrodsburg, KY parcel')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Multiple tel. conf. w/ brokers re BOV for 2229 Muscatine, Iowa City, IA parcel')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich re 2229 Muscatine, Iowa City, IA property conveyance')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ Harrodsburg, KY tax assessment and planning offices regarding zoning restrictions and tax assessed value of 102 N. College St.')
    WorkEntry.create(code: code, worked_at: '2011-11-22', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ prospective purchaser of 8005 N. May, Oklahoma  City, OK')
    WorkEntry.create(code: code, worked_at: '2011-11-25', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Prepare inquiry response re Owned Service Station #203, Aberdeen, SD')
    WorkEntry.create(code: code, worked_at: '2011-11-28', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Prepare several property purchase and lease inquiry response letters re owned service station sites')
    WorkEntry.create(code: code, worked_at: '2011-11-28', minutes: 225, rate_cents: nil, fee_cents: nil, note: 'Prepare memorandum in support of property transaction for Harrodsburg, KY; email M. Fryer re same')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review M. Mehlhoff and M. Weinreich corresp. re 1802 6th Ave. NE, Aberdeen property inquiry')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email M. Fryer re Harrosburg, KY prospective conveyance (102 N. College St.)')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ A. Wingfield regarding interest in Arkadelphia, AK site')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email K. Eckert re info re 8005 N. May, Oklahoma City, OK')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. and email w/ prospective lessee for 4525 Washington Ave., Houston TX site')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ prospective purchasers of Harrodsburg, KY, Oklahoma City, OK and Arkadelphia, AK sites')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Emails to prospective purchaser of 4525 Washington Ave., Houston, TX site')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Respond to six purchase inquiries re owned service stations')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Two tel. conf. w/ M. Fryer re Harrodsburg conveyance')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 150, rate_cents: nil, fee_cents: nil, note: 'Research (incuding phone calls to prospective purchaser, tax assessor, and planning department, and reviewing all documents forwarded by prospective purchaser) and prepare memorandum in support of property transaction for Harrodsburg, KY')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Review and discuss w/ M. Weinreich leasing inquiry re 4525 Washingon Ave., Houston, TX site')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Several emails w/ prospective purchaser of 8005 N. May, Oklahoma City, OK site')
  code = Code.create(location: loc, code: 'XXXI.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXXI.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'MST Work ECA')
  code = Code.create(location: loc, code: 'XXXII.A', name: 'Regulatory Compliance')
  code = Code.create(location: loc, code: 'XXXII.B', name: 'O & M')
  code = Code.create(location: loc, code: 'XXXII.C', name: 'New Environmental Actions')
  code = Code.create(location: loc, code: 'XXXII.D', name: 'MST Technical Team/Project Mgmt')
  code = Code.create(location: loc, code: 'XXXII.E', name: 'Trustee Fees & Expenses')
  code = Code.create(location: loc, code: 'XXXII.F', name: 'Regulator Oversight Costs')
  code = Code.create(location: loc, code: 'XXXII.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Review corresp. re traffic accident and damage at 2025 N. Clifton, Springfield site; email T. Griffith re same')
    WorkEntry.create(code: code, worked_at: '2011-11-10', minutes: 165, rate_cents: nil, fee_cents: nil, note: 'Review M. Branstetter correspondence re proposed mining rights acquisition on Missouri properties')
    WorkEntry.create(code: code, worked_at: '2011-11-11', minutes: 75, rate_cents: nil, fee_cents: nil, note: 'Review documents relative to M. Branstetter/Northern Land offer re MO mineral rights')
    WorkEntry.create(code: code, worked_at: '2011-11-14', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review Athens Drive, Nashville materials from prospective purchaser; email M. Weinreich re same')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. with D. Danforth re interest in leasing Florida parcel')
  code = Code.create(location: loc, code: 'XXXII.H', name: 'Accounting Costs')
  code = Code.create(location: loc, code: 'XXXII.I', name: 'Lease & Property Use - Inc & Exp')
loc = Location.create(name: 'MST AA')
  code = Code.create(location: loc, code: 'I.A', name: 'Financial Affairs')
  code = Code.create(location: loc, code: 'I.B', name: 'Taxes')
    WorkEntry.create(code: code, worked_at: '2011-11-01', minutes: 75, rate_cents: nil, fee_cents: nil, note: 'Review info re personal property taxes at multiple owned sites')
  code = Code.create(location: loc, code: 'I.C', name: 'Site Security & Property Mgmt')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email M. Weinreich re property mowing invoice follow-up')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Email J. Pinkus re procedures for working with mowers; research existing mowing contracts on Alfresco')
  code = Code.create(location: loc, code: 'I.C.10', name: 'Site Security & Property Mgmt:I.C.10 - Indianapolis ECA')
  code = Code.create(location: loc, code: 'I.C.11', name: 'Site Security & Property Mgmt:I.C.11 - Rushville ECA')
  code = Code.create(location: loc, code: 'I.C.12', name: 'Site Security & Property Mgmt:I.C.12 - Bossier City ECA')
  code = Code.create(location: loc, code: 'I.C.13', name: 'Site Security & Property Mgmt:I.C.13 - Calhoun ECA')
  code = Code.create(location: loc, code: 'I.C.14', name: 'Site Security & Property Mgmt:I.C.14 - Kansas City ECA')
  code = Code.create(location: loc, code: 'I.C.15', name: 'Site Security & Property Mgmt:I.C.15 - Springfield ECA')
  code = Code.create(location: loc, code: 'I.C.16', name: 'Site Security & Property Mgmt:I.C.16 - Columbus ECA')
  code = Code.create(location: loc, code: 'I.C.17', name: 'Site Security & Property Mgmt:I.C.17 - Columbus SA')
  code = Code.create(location: loc, code: 'I.C.18', name: 'Site Security & Property Mgmt:I.C.18 - Meridian ECA')
  code = Code.create(location: loc, code: 'I.C.19', name: 'Site Security & Property Mgmt:I.C.19 - Meridian SA')
  code = Code.create(location: loc, code: 'I.C.2', name: 'Site Security & Property Mgmt:I.C.2 - Birmingport ECA')
  code = Code.create(location: loc, code: 'I.C.20', name: 'Site Security & Property Mgmt:I.C.20 - Navassa ECA')
  code = Code.create(location: loc, code: 'I.C.21', name: 'Site Security & Property Mgmt:I.C.21 - Navassa SA')
  code = Code.create(location: loc, code: 'I.C.22', name: 'Site Security & Property Mgmt:I.C.22 - Bristol ECA')
  code = Code.create(location: loc, code: 'I.C.23', name: 'Site Security & Property Mgmt:I.C.23 - Caselton ECA')
  code = Code.create(location: loc, code: 'I.C.24', name: 'Site Security & Property Mgmt:I.C.24 - Rome ECA')
  code = Code.create(location: loc, code: 'I.C.25', name: 'Site Security & Property Mgmt:I.C.25 - Cleveland ECA')
  code = Code.create(location: loc, code: 'I.C.26', name: 'Site Security & Property Mgmt:I.C.26 - Cushing ECA')
  code = Code.create(location: loc, code: 'I.C.27', name: 'Site Security & Property Mgmt:I.C.27 - Avoca ECA')
  code = Code.create(location: loc, code: 'I.C.28', name: 'Site Security & Property Mgmt:I.C.28 - Beaumont ECA')
  code = Code.create(location: loc, code: 'I.C.29', name: 'Site Security & Property Mgmt:I.C.29 - Corpus Christi ECA')
  code = Code.create(location: loc, code: 'I.C.3', name: 'Site Security & Property Mgmt:I.C.3 - Mobile ECA')
  code = Code.create(location: loc, code: 'I.C.30', name: 'Site Security & Property Mgmt:I.C.30 - Texarkana ECA')
  code = Code.create(location: loc, code: 'I.C.31', name: 'Site Security & Property Mgmt:I.C.31 - Owned Service Stations ECA')
  code = Code.create(location: loc, code: 'I.C.32', name: 'Site Security & Property Mgmt:I.C.32 - MST Work Acct')
  code = Code.create(location: loc, code: 'I.C.4', name: 'Site Security & Property Mgmt:I.C.4 - Jacksonville AgCh ECA')
  code = Code.create(location: loc, code: 'I.C.5', name: 'Site Security & Property Mgmt:I.C.5 - Jacksonville AgCh SA')
  code = Code.create(location: loc, code: 'I.C.6', name: 'Site Security & Property Mgmt:I.C.6 - Jacksonsonville PT ECA')
  code = Code.create(location: loc, code: 'I.C.7', name: 'Site Security & Property Mgmt:I.C.7 - Soda Springs ECA')
  code = Code.create(location: loc, code: 'I.C.8', name: 'Site Security & Property Mgmt:I.C.8 - Madison ECA')
  code = Code.create(location: loc, code: 'I.C.9', name: 'Site Security & Property Mgmt:I.C.9 - Sauget ECA')
  code = Code.create(location: loc, code: 'I.D', name: 'Insurance')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 75, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ P. Transue re property insurance policies; review documents on Alfresco relative to same')
  code = Code.create(location: loc, code: 'I.E', name: 'Trustee Fee & Expenses')
  code = Code.create(location: loc, code: 'I.F', name: 'Legal Affairs')
    WorkEntry.create(code: code, worked_at: '2011-11-01', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Email and tel. conf. w/ P. Transue and C. Neuberger and K. Eckert re personal property taxes at sites')
    WorkEntry.create(code: code, worked_at: '2011-11-02', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email P. Transue re property tax spreadsheet')
    WorkEntry.create(code: code, worked_at: '2011-11-02', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review P. Transue property tax spreadsheet')
    WorkEntry.create(code: code, worked_at: '2011-11-03', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Review email corresp.re various site-related bills for personal property and real estate tax matters')
    WorkEntry.create(code: code, worked_at: '2011-11-05', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich re property tax related issues')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Rmail B. Leaf for wire instructions re transfer of Tronox assets into various MST accounts')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review corresp. re transfer of Tronox assets into various MST accounts')
    WorkEntry.create(code: code, worked_at: '2011-11-08', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review corresp. re Chatham County tax bills; forward same to C. Neuberger and P. Transue')
    WorkEntry.create(code: code, worked_at: '2011-11-09', minutes: 75, rate_cents: nil, fee_cents: nil, note: 'Corresp. w/ S. Denlinger re MST accounts for depositing Tronox proceeds')
    WorkEntry.create(code: code, worked_at: '2011-11-09', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Participate in conference call w/ P. Transue, K. Hey, C. Neuberger and S. Denlinger re property tax issues')
    WorkEntry.create(code: code, worked_at: '2011-11-10', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review C. Neuberger tax property meeting summary and memo re invoicing procedures')
    WorkEntry.create(code: code, worked_at: '2011-11-11', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Discuss wire instructions re Tronox proceeds with S. Denlinger')
    WorkEntry.create(code: code, worked_at: '2011-11-11', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Prepare corresp. re five property purchase inquiries')
    WorkEntry.create(code: code, worked_at: '2011-11-11', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review Notices of Violation regarding several owned service stations; corresp. w/ K. Eckhart and C. Neuberger re same')
    WorkEntry.create(code: code, worked_at: '2011-11-14', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Paque re liquidation and transfer of Tronox assets into various MST accounts')
    WorkEntry.create(code: code, worked_at: '2011-11-15', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Review and comment on C. Neuberger summary of property tax payment procedures')
    WorkEntry.create(code: code, worked_at: '2011-11-16', minutes: 75, rate_cents: nil, fee_cents: nil, note: 'Review M. Weinreich and C. Neuberger corresp. re property tax bills')
    WorkEntry.create(code: code, worked_at: '2011-11-16', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Email S. Denlinger and M. Paque re wire transfer instructions for Tronox assets')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review M. Weinreich comments on C. Neuberger summary re payment of real estate taxes')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Review M. Weinreich summary re procedures for wire transfers')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich re real estate tax related issues')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Email M. Paque and M. Weinreich corresp. re wire transfer instructions for Treasury Partners accounts')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Review Trust Agreement and Settlement Agreement re procedures for disposition of sale proceeds from owned properties')
    WorkEntry.create(code: code, worked_at: '2011-11-17', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email M. Paque re delays in Sauget and Springfield liquidation and transfer of assets')
    WorkEntry.create(code: code, worked_at: '2011-11-18', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich and J. Pinkus regarding procedures for handling mowing invoices, property inquiries, and vendors')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Discuss ATECH agreement with M. Weinreich')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Revise template of lease inquiry response form; upload to Alfresco')
    WorkEntry.create(code: code, worked_at: '2011-11-25', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Review C. Neuberger correspondence re property tax bills')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 150, rate_cents: nil, fee_cents: nil, note: 'Update property inquiry spreadsheet')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ J. Pinkus and M. Weinreich re real estate property tax payment procedures')
    WorkEntry.create(code: code, worked_at: '2011-11-29', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email P. Cheathem re Lamar leases')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. and emails w/ P. Transue and M. Weinreich re property tax payment conference call and procedural matters')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review correspondence regarding tax bills for owned sites')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Prepare summary regarding property tax payment protocols; email M. Weinreich re same')
    WorkEntry.create(code: code, worked_at: '2011-11-30', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ C. Neuberger re property tax payment protocols')
  code = Code.create(location: loc, code: 'I.G', name: 'Overall Trust IT/Records/Docs')
  code = Code.create(location: loc, code: 'I.H', name: 'Pre-Effective Date Fees & Exps')
  code = Code.create(location: loc, code: 'I.I', name: 'MST Leases')
    WorkEntry.create(code: code, worked_at: '2011-11-18', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Email M. Weinreich re lease inquiries; prepare draft lease inquiry response letter')
loc = Location.create(name: 'Unknown')
  code = Code.create(location: loc, code: 'Unknown', name: 'Unknown')
    WorkEntry.create(code: code, worked_at: '2011-12-01', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Review tax abatement correspondence; email M. Weinreich and C. Neuberger re same')
    WorkEntry.create(code: code, worked_at: '2011-12-01', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich re property tax management issues')
    WorkEntry.create(code: code, worked_at: '2011-12-01', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Corresp. w/ P. Transue re scanned documents covering owned service stations')
    WorkEntry.create(code: code, worked_at: '2011-12-01', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Review 8005 N. May, Oklahoma City, OK conveyance-related documents; prepare email to J. Pinkus re  BOV for same')
    WorkEntry.create(code: code, worked_at: '2011-12-02', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ D. Danforth re Polk County, FL parcel')
    WorkEntry.create(code: code, worked_at: '2011-12-02', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Corresp. w/ prospective purchaser re 4525 Wash. Ave., Houston, TX parcel')
    WorkEntry.create(code: code, worked_at: '2011-12-02', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Fryer re Harrodsburg, KY proposed conveyance')
    WorkEntry.create(code: code, worked_at: '2011-12-02', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Prepare Harrodsburg, KY Memorandum in Support of Property Sale')
    WorkEntry.create(code: code, worked_at: '2011-12-04', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Follow up re insurance policy covering Texarkana site and wire theft')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Discuss timekeeping procedures with M. Weinreich')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Review C. Neuberger memorandum re invoice payment procedures')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'View Alfresco webinar; email P. Transue re same')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Research Kokomo, IN documents on Alfresco in connection with proposed easement')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Email K. Eckert re proposed Kokomo easement')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Review 2229 Muscatine Avenue, Iowa City, IA materials from S. Holocek; start preparing Memorandum in Support of Property Transaction; email S. Holocek re same')
    WorkEntry.create(code: code, worked_at: '2011-12-05', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Prepare Harrodsburg deed from MST into purchaser; email M. Fryer re same')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ Austin Wingfield and Roger Wingfield re Arkadelphia site')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Follow up re correspondence re 8800 Minors Lane, Louisville, KY')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Email C. Neuberger and M. Weinreich re real estate tax payment protocols')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Revise and email  to M. Weinreich draft Harrodsburg, KY Memorandum in Support of Sale and accompanying documents')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Several emails w/ M. Fryer re Harrodsburg, KY conveyance')
    WorkEntry.create(code: code, worked_at: '2011-12-06', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Email P. Transue re converting pdf files to word files for template documents')
    WorkEntry.create(code: code, worked_at: '2011-12-07', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ K. Hey')
    WorkEntry.create(code: code, worked_at: '2011-12-07', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ P.  Transue re real estate property tax spreadsheet')
    WorkEntry.create(code: code, worked_at: '2011-12-07', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ C. Brooks and M. Weinreich re property tax protocols')
    WorkEntry.create(code: code, worked_at: '2011-12-07', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Rrview corresp. From C. Neuberger relative to property tax-related matters')
    WorkEntry.create(code: code, worked_at: '2011-12-08', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Email K. Eckert re 8800 Minors Lane, Louisville property')
    WorkEntry.create(code: code, worked_at: '2011-12-08', minutes: 0, rate_cents: nil, fee_cents: nil, note: 'Review right of way request re Payne, OK')
loc = Location.create(name: 'Savannah ECA')
  code = Code.create(location: loc, code: 'S.I.G', name: 'Legal Costs')
    WorkEntry.create(code: code, worked_at: '2011-11-01', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email w/ P. Rowland re Savannah railcar storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-01', minutes: 45, rate_cents: nil, fee_cents: nil, note: 'Review P. Rowland comments on Savannah railcar storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-05', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Tel. conf. w/ M. Weinreich re Kemira lease')
    WorkEntry.create(code: code, worked_at: '2011-11-05', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Email discussion w/ P. Rowland re Savannah railcar storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review M. Weinreich changes to rail car storage agreement for Savannah and incorporate changes into final agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Review corresp. re real estate tax bills for Savannah')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 60, rate_cents: nil, fee_cents: nil, note: 'Respond to lessee comments on Savannah rail car storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-16', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Review agenda for biweekly Savannah conference call; email M. Weinreich and P. Rowland re same')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Review P. Rowland corresp. re Savannah railcar storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-21', minutes: 135, rate_cents: nil, fee_cents: nil, note: 'Review Savannah and MST tax abatement agreements; email M. Weinreich re same')
loc = Location.create(name: 'Savannah AA')
  code = Code.create(location: loc, code: 'S.II.F', name: 'Legal Affairs')
    WorkEntry.create(code: code, worked_at: '2011-11-04', minutes: 90, rate_cents: nil, fee_cents: nil, note: 'Corresp. w/ P. Rowland re proposed modifications to Savannah railcar storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 105, rate_cents: nil, fee_cents: nil, note: 'Review Assessment Technologies correspondence re Savannah tax matters')
    WorkEntry.create(code: code, worked_at: '2011-11-07', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Review EPA corresp. re approval of Savannah rail car storage agreement')
    WorkEntry.create(code: code, worked_at: '2011-11-09', minutes: 30, rate_cents: nil, fee_cents: nil, note: 'Review corresp.from C. Neubeger and P. Rowland re Savannah real estate tax bills')
    WorkEntry.create(code: code, worked_at: '2011-11-09', minutes: 15, rate_cents: nil, fee_cents: nil, note: 'Email P. Rowland re tank remediation required at Savannah')
